apiVersion: apps/v1
kind: Deployment
metadata:
  name: finmate-api
  labels:
    app.kubernetes.io/name: finmate
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: finmate
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: finmate
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: __API_IMAGE__
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: finmate-api-secret
                  key: DB_PASSWORD
            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: finmate-api-secret
                  key: CLOUD_API_KEY
            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: finmate-api-secret
                  key: CLOUD_API_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: finmate-api-secret
                  key: JWT_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: finmate-api-secret
                  key: GOOGLE_CLIENT_ID
