apiVersion: v1
kind: Service
metadata:
  name: {{ include "finmate.fullname" . }}-api
  labels:
    {{- include "finmate.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "finmate.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
