{{- if .Values.api.secret.create -}}
{{- $secretName := default (printf "%s-api" (include "finmate.fullname" .)) .Values.api.secret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "finmate.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
stringData:
  {{- range $key, $value := .Values.api.secret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
