apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finmate.fullname" . }}-web
  labels:
    {{- include "finmate.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.replicaCount.web }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "finmate.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "finmate.labels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: "{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}"
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.web.port }}
          resources:
            {{- toYaml .Values.resources.web | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
